name: black_cat_lib
description: Personal library with custom widgets and extensions.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

  flutter: ">=2.0.0"

dependencies:
  dart_date: ^1.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  iphone_has_notch: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
